name = "example"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
midas_node = { path = "../"}
midas = ">= 1.2.0 and < 2.0.0"
plinth = ">= 0.5.1 and < 1.0.0"
snag = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
